##########################################
# Global containers
##########################################

# phpmyadmin for admin database
'phpmyadmin':
    image: 'nazarpc/phpmyadmin:latest'
    container_name: 'phpmyadmin'
    environment:
      - ALLOW_ARBITRARY=1
      - URL=phpmyadmin.blog
    restart: always
    links: ['mysql_auth', 'mysql_blog']
    ports: ['30000:80']

# database for service `auth`
'mysql_auth':
    image: 'mysql:5.6.26'
    container_name: 'mysql_auth'
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes: [/var/lib/mysql]

# database for service `Comment` and `Post`
'mysql_blog':
    image: 'mysql:5.6.26'
    container_name: 'mysql_blog'
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes: [/var/lib/mysql]

# redis for fast cache
'redis':
    image: 'redis'
    container_name: 'redis'

##########################################
# Service `Gate`
##########################################

# source code storage for `gate`
'source_gate':
    build: 'source'
    container_name: 'source_gate'
    environment:
      - SSH_USER=gregory
      - SSH_PASSWORD=root
      - SSH_PORT=22
    volumes: ['../Services/Gate:/home/gregory/source/']

# php for `Gate`
'php_gate':
    build: 'php'
    container_name: 'php_gate'
    volumes_from: ['source_gate']
    volumes: ['./logs/php/gate/:/var/log/dev_php']

# nginx for `Gate`
'nginx_gate':
    build: 'nginx'
    container_name: 'nginx_gate'
    links: ['php_gate']
    volumes_from: ['source_gate']
    ports: ['30001:80']
    environment:
      - PHP_HOST=php_gate
      - NGINX_HOST_TEMPLATE=gate.blog
    volumes: ['./logs/nginx/gate/:/var/log/nginx']

##########################################
# Service `Post 1`
##########################################

# source code storage for `Post 1`
'source_post_1':
    build: 'source'
    container_name: 'source_post_1'
    environment:
      - SSH_USER=gregory
      - SSH_PASSWORD=root
      - SSH_PORT=22
    volumes: ['../Services/Post:/home/gregory/source/']

# php for `Post 1`
'php_post_1':
    build: 'php'
    container_name: 'php_post_1'
    volumes_from: ['source_post_1']
    links: ['mysql_blog']
    volumes: ['./logs/php/post_1/:/var/log/dev_php']
    environment:
      - PDO_CONNECT=mysql:host=mysql_blog;dbname=blog
      - PDO_USER=root
      - PDO_PASSWORD=root

# nginx for `Post 1`
'nginx_post_1':
    build: 'nginx'
    container_name: 'nginx_post_1'
    links: ['php_post_1']
    volumes_from: ['source_post_1']
    ports: ['30002:80']
    environment:
      - PHP_HOST=php_post_1
      - NGINX_HOST_TEMPLATE=post.blog
    volumes: ['./logs/nginx/post_1/:/var/log/nginx']

##########################################
# Service `Post 2`
##########################################

# source code storage for `Post 2`
'source_post_2':
    build: 'source'
    container_name: 'source_post_2'
    environment:
      - SSH_USER=gregory
      - SSH_PASSWORD=root
      - SSH_PORT=22
    volumes: ['../Services/Post:/home/gregory/source/']

# php for `Post 2`
'php_post_2':
    build: 'php'
    container_name: 'php_post_2'
    volumes_from: ['source_post_2']
    links: ['mysql_blog']
    volumes: ['./logs/php/post_2/:/var/log/dev_php']
    environment:
      - PDO_CONNECT=mysql:host=mysql_blog;dbname=blog
      - PDO_USER=root
      - PDO_PASSWORD=root

# nginx for `Post 2`
'nginx_post_2':
    build: 'nginx'
    container_name: 'nginx_post_2'
    links: ['php_post_2']
    volumes_from: ['source_post_2']
    ports: ['30003:80']
    environment:
      - PHP_HOST=php_post_2
      - NGINX_HOST_TEMPLATE=post.blog
    volumes: ['./logs/nginx/post_2/:/var/log/nginx']